apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: icanhazip-go
  name: icanhazip-go
spec:
  selector:
    app: icanhazip-go
    deploymentconfig: icanhazip-go
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: icanhazip-go
        deploymentconfig: icanhazip-go
    spec:
      containers:
      - image: icanhazip-go
        imagePullPolicy: Always
        name: icanhazip-go
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - icanhazip-go
      from:
        kind: ImageStreamTag
        name: icanhazip-go:latest
    type: ImageChange

