kind: "Service"
apiVersion: "v1"
metadata:
  name: "external-whatismyip"
spec:
  ports:
    -
      name: "icanhazip"
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 0
selector: {} 
